#Independent settings for the planner's costmap

global_costmap:
  #Set the global and robot frames for the costmap
  global_frame: /map
  robot_base_frame: base_link

  #Set the update and publish frequency of the costmap
  update_frequency: 3.0
  publish_frequency: 0.0

  #We'll use a map served by the map_server to initialize this costmap
  static_map: false
  rolling_window: true

  footprint_padding: 0.01
