transform_tolerance: 0.2
sim_time: 1.7
sim_granularity: 0.025
dwa: true
vx_samples: 3
vtheta_samples: 20
goal_distance_bias: 0.8
path_distance_bias: 0.6
occdist_scale: 0.01
heading_lookahead: 0.325
oscillation_reset_dist: 0.5#0.05
acc_lim_th: 2.5
acc_lim_x: 4.0
acc_lim_y: 1.0
max_vel_x: 0.4
min_vel_x: 0.3
max_rotational_vel: 1.1
min_in_place_rotational_vel: 0.5
holonomic_robot: true
controller_frequency: 10.0
xy_goal_tolerance: 0.5
yaw_goal_tolerance: 0.1
