TrajectoryPlannerROS:
  # Robot Configuration Parameters 
  acc_lim_x: 0.1
  acc_lim_y: 0.1
  acc_lim_theta: 0.6
  max_vel_x: 0.55
  min_vel_x: 0.2
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.2
  escape_vel: -0.1
  holonomic_robot: false
  y_vels: [-0.3,-0.1,0.1,0.3]

  # Goal Tolerance Parameters 
  yaw_goal_tolerance: 0.35
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: true

  # Forward Simulation Parameters
  sim_time: 1.7
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 3
  vtheta_samples: 20
  controller_frequency: 10.0

  # Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.01
  heading_lookahead: 0.9 # 0.325
  heading_scoring: false
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid_pc: false
  global_frame_id: odom

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

  # Global Plan Parameters
  prune_plan: true

